language: java
jdk:
- oraclejdk8
notifications:
  slack: webcrawler:LIBCqQxYwgWEhIPZGxk7N0oE
branches:
  only:
  - master
  - dev
  - feature/#3_configure_travis

#script: (cd frontend && npm install)

before_deploy: (mvn install && tree)

# deploy:
#   skip_cleanup: true
#   provider: elasticbeanstalk
#   access_key_id: AKIAIDGGEWLKEAEKPHEQ
#   secret_access_key: $AWS_KEY
#   region: us-west-2
#   app:  WebCrawler-BS
#   env: webcrawlerbs
#   bucket_name: elasticbeanstalk-us-west-2-493126854002
#   on:
#     repo: radekkut/WebCrawler
#     branch: feature/#3_configure_travis

deploy:
  provider: s3
  access_key_id: AKIAIDGGEWLKEAEKPHEQ
  secret_access_key: $AWS_KEY
  bucket: elasticbeanstalk-us-west-2-493126854002
  skip_cleanup: true
  region: us-west-2
  on:
    repo: radekkut/WebCrawler
    branch: feature/#3_configure_travis
  