language: java
jdk:
- oraclejdk8
notifications:
  slack: webcrawler:LIBCqQxYwgWEhIPZGxk7N0oE
branches:
  only:
  - master
  - dev
  - feature/#3_configure_travis

env:
  global:
   - secure: "bCeV+NtOTKizZd6A2noxUA1HbKFY5ITPq00DQllY4W5r/Tt4SnWPTNANdLQKWDjG6FKCMfYd6XhnEKQweNGJ2Ej22vPWkJnaoIhP24kiH890emjTC0uEB5EMBCLu0T8Y0Q5qIWzCD7TO7lIOHCAyIMx7JEHslUTDShUFp/EvfsEKoGRZyG7DJ+I6ijSMqt5tCrY8wTkvPhBbH+/F8Brw0lYKB7JYllsu8Jh5aHsshxgctOGTG9ZU9OZwFqFc7k3USIRkScdXhwMSEzZB5m5UCWsesFj4iU03HWu5nfHIj8Imkr59qZycg+MckqXEMEXJqiNmK3O+LoZu7Fw+gIVtE5jHUO9X4Ct5LSd0Xzhn8kVX4JxDLU/eh3vFc20FxDmiHCls03Z22v+Y9FophHs7M9TLNBmr6bFowWlKg6BDIsITfWLCx9S5O9E3bMpq0Bn3qjbC16sukkR58W99d9JNKnotwx0r08JNBSM0dCHxBhSA7hKEVvTrdSAkEha1FWeEyOk2i4/jYk+2juxiH01XwpKK9dMp6NVSDKvfcJ8VS+1nit/vZP3Kv8nrZ6rnvx8VMkMj2/11sHtc7FDYC2yLpDd6xq1t5Ovq/2Fu0DkDD+QOfGYVr2OYNJVHEilak5nzD5P3Pqrq7tFU3e/FVxqFsTFtfd9g7TDzkiyF4eiZ0Tc="

before-deploy: (cd frontend && npm install)

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIDGGEWLKEAEKPHEQ
  secret_access_key: $AWS_KEY
  region: us-west-2
  app:  WebCrawler-BS
  env: webcrawlerbs
  bucket_name: elasticbeanstalk-us-west-2-493126854002
  on:
    repo: radekkut/WebCrawler
    branch: feature/#3_configure_travis


addons:
  coverity_scan:
    project:
      name: "radekkut/WebCrawler"
      description: "Build submitted via Travis CI"
    notification_email: radoslaw.kutylowski@stermedia.pl
    build_command_prepend: "mvn clean"
    build_command:   "mvn compile"
    branch_pattern: develop
