language: java
jdk:
- oraclejdk8
notifications:
  slack: webcrawler:LIBCqQxYwgWEhIPZGxk7N0oE
deploy:
  provider: codedeploy
  access_key_id: AKIAIWLXXTE27EVKXWKA
  secret_access_key: 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
  application: WebCrawler-App
  deployment_group: WebCrawler-DepGrp
  region: us-west-2
  on:
    repo: radekkut/WebCrawler
    branch: feature/#3_configure_travis